[package]
name = "domain"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.63"
nom = "7.1.1"
[lib]
crate-type = ["lib"]